spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sf
    username: root
    password: ww123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc:
    template:
      query-timeout: 3
  redis:
    port: 6379
    host: localhost
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.ww.backend: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
#  type-aliases-package: com.ww.backend.*.entity




